# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleC <- function(X) {
    .Call(`_Scissor_scaleC`, X)
}

OmegaC <- function(Omega, sgn) {
    .Call(`_Scissor_OmegaC`, Omega, sgn)
}

OmegaSC <- function(OmegaS, sgn) {
    .Call(`_Scissor_OmegaSC`, OmegaS, sgn)
}

maxLambdaLmC <- function(X, y, alpha, wbeta, N0, p) {
    .Call(`_Scissor_maxLambdaLmC`, X, y, alpha, wbeta, N0, p)
}

cvTrimLmC <- function(beta, nn, nn2, loco, XF, yF, NF, a0) {
    .Call(`_Scissor_cvTrimLmC`, beta, nn, nn2, loco, XF, yF, NF, a0)
}

EnetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, p, N0, thresh, maxit, thresh2) {
    .Call(`_Scissor_EnetLmC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, p, N0, thresh, maxit, thresh2)
}

cvEnetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call(`_Scissor_cvEnetLmC`, X, y, alpha, lambda, nlambda, wbeta, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

NetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, p, N0, thresh, maxit, thresh2) {
    .Call(`_Scissor_NetLmC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, p, N0, thresh, maxit, thresh2)
}

cvNetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call(`_Scissor_cvNetLmC`, X, y, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

maxLambdaCoxC <- function(X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p) {
    .Call(`_Scissor_maxLambdaCoxC`, X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p)
}

pletaCm <- function(xb, exb, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call(`_Scissor_pletaCm`, xb, exb, nevent, nevent1, loc1, n, ifast, itwo)
}

cvTrimCoxC <- function(beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call(`_Scissor_cvTrimCoxC`, beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo)
}

EnetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call(`_Scissor_EnetCoxC`, X, tevent, alpha, lambda, nlambda, ilambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvEnetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call(`_Scissor_cvEnetCoxC`, X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

NetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call(`_Scissor_NetCoxC`, X, tevent, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvNetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call(`_Scissor_cvNetCoxC`, X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

maxLambdaLogC <- function(X, Z, alpha, wbeta, N0, p) {
    .Call(`_Scissor_maxLambdaLogC`, X, Z, alpha, wbeta, N0, p)
}

cvTrimLogC <- function(beta, nn, nn2, loco, XF, yF, NF, threshP) {
    .Call(`_Scissor_cvTrimLogC`, beta, nn, nn2, loco, XF, yF, NF, threshP)
}

EnetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP) {
    .Call(`_Scissor_EnetLogC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP)
}

cvEnetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call(`_Scissor_cvEnetLogC`, X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

NetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP) {
    .Call(`_Scissor_NetLogC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP)
}

cvNetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call(`_Scissor_cvNetLogC`, X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_Scissor_RcppExport_registerCCallable', PACKAGE = 'Scissor')
})
